.gitignore
NOTICE.md
charts/ephemeral/README.md
charts/ephemeral/templates/discovery.yaml
charts/ephemeral/templates/ephemeral.yaml
charts/ephemeral/values.yaml
cmd/discovery/main.go
cmd/discovery/main_test.go
cmd/ephemeral/main.go
cmd/ephemeral/main_test.go
pkg/discovery/discovery.go
pkg/discovery/discovery_test.go
pkg/discovery/game.go
pkg/discovery/game_test.go
pkg/discovery/networker.go
pkg/discovery/test_helpers.go
pkg/ephemeral/fake_spdz_test.go
pkg/ephemeral/network/proxy.go
pkg/ephemeral/network/proxy_test.go
pkg/ephemeral/network/tcpchecker.go
pkg/ephemeral/server.go
pkg/ephemeral/spdz.go
pkg/ephemeral/spdz_test.go
pkg/integration/discovery_ephemeral_integration.go
pkg/integration/discovery_master_slave_integration.go
pkg/types/types.go
pkg/utils/os.go
pkg/utils/os_test.go

To use more than 2 players, it's required to create new crypto-material with given number of players e.g. for 3 players. This also means that the base-image of ephemeral needs to be rebuild including the new crypto-material!
The helm chart is using 2 players as a default, so the current deployment stays with 2 players.
requires https://github.com/carbynestack/ephemeral/pull/19

enhance ephemeral to work with more than 2 players

---

.release-please-manifest.json
CHANGELOG.md

---
* **service/chart/java-client:** test release logic ([#39](https://github.com/carbynestack/ephemeral/issues/39)) ([9c8f07b](https://github.com/carbynestack/ephemeral/commit/9c8f07b53f7f9792ad2b484b25666c1a4244303d))
---

chore: release  service 0.1.1

---

.release-please-manifest.json
charts/ephemeral/CHANGELOG.md
charts/ephemeral/Chart.yaml

---
* **service/chart/java-client:** test release logic ([#39](https://github.com/carbynestack/ephemeral/issues/39)) ([9c8f07b](https://github.com/carbynestack/ephemeral/commit/9c8f07b53f7f9792ad2b484b25666c1a4244303d))
---

chore: release  chart 0.1.1

---

.release-please-manifest.json
ephemeral-java-client/CHANGELOG.md
ephemeral-java-client/pom.xml

---
* **service/chart/java-client:** test release logic ([#39](https://github.com/carbynestack/ephemeral/issues/39)) ([9c8f07b](https://github.com/carbynestack/ephemeral/commit/9c8f07b53f7f9792ad2b484b25666c1a4244303d))
---

chore: release  java-client 0.1.1

---

.release-please-manifest.json
ephemeral-java-client/CHANGELOG.md
ephemeral-java-client/pom.xml

---
* **service/chart/java-client:** test release logic with some minor fixes ([#46](https://github.com/carbynestack/ephemeral/issues/46)) ([a215b6b](https://github.com/carbynestack/ephemeral/commit/a215b6b884ea73fc69f4283aca849dbc8bf520d4))
---

chore: release  java-client 0.1.2

---

.release-please-manifest.json
charts/ephemeral/CHANGELOG.md
charts/ephemeral/Chart.yaml

---
* **service/chart/java-client:** test release logic with some minor fixes ([#46](https://github.com/carbynestack/ephemeral/issues/46)) ([a215b6b](https://github.com/carbynestack/ephemeral/commit/a215b6b884ea73fc69f4283aca849dbc8bf520d4))
---

chore: release  chart 0.1.2

---

.release-please-manifest.json
CHANGELOG.md

---
* **service/java-client:** add support for partial builds using codeco… ([#52](https://github.com/carbynestack/ephemeral/issues/52)) ([5a7a591](https://github.com/carbynestack/ephemeral/commit/5a7a591c5d81daf8bad09826b9c9f8bfcbe73eee))
---

chore: release  service 0.1.3

---

.release-please-manifest.json
ephemeral-java-client/CHANGELOG.md
ephemeral-java-client/pom.xml

---
* **service/java-client:** add support for partial builds using codeco… ([#52](https://github.com/carbynestack/ephemeral/issues/52)) ([5a7a591](https://github.com/carbynestack/ephemeral/commit/5a7a591c5d81daf8bad09826b9c9f8bfcbe73eee))
---

chore: release  java-client 0.1.3

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** update publish workflow to use correct working directory ([#55](https://github.com/carbynestack/ephemeral/issues/55)) ([0727a99](https://github.com/carbynestack/ephemeral/commit/0727a99081ee96f49b42fa45e72a30f0a6147548))
---

chore: release  service 0.1.4

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** fix publish workflow for service ([#57](https://github.com/carbynestack/ephemeral/issues/57)) ([570b6b6](https://github.com/carbynestack/ephemeral/commit/570b6b6a701687aa0d76adfe8b54540f16884cb1))
---

chore: release  service 0.1.5

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** add missing '=' when invoking ko ([#59](https://github.com/carbynestack/ephemeral/issues/59)) ([ebe4c84](https://github.com/carbynestack/ephemeral/commit/ebe4c8472a3883917dbc562cc7e571141ca55bd2))
---

chore: release  service 0.1.6

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** test without labels ([#63](https://github.com/carbynestack/ephemeral/issues/63)) ([5e1f1fa](https://github.com/carbynestack/ephemeral/commit/5e1f1fa14a7677e93253264bc3ba31a4c569227b))
---

chore: release  service 0.1.8

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** generate both tags and lables for ko correctly ([#65](https://github.com/carbynestack/ephemeral/issues/65)) ([1ccac01](https://github.com/carbynestack/ephemeral/commit/1ccac012cff5c4ce7bcf4de854515116a872b51c))
---

chore: release  service 0.1.9

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** quote tags and labels argument to make ko working ([#69](https://github.com/carbynestack/ephemeral/issues/69)) ([973f067](https://github.com/carbynestack/ephemeral/commit/973f0673003530aae9a693f0799a6008850b269a))
---

chore: release  service 0.1.11

---

.release-please-manifest.json
CHANGELOG.md

---
* **service:** extract the label part from what is returned by the metadata action ([#71](https://github.com/carbynestack/ephemeral/issues/71)) ([2243f0f](https://github.com/carbynestack/ephemeral/commit/2243f0f113e96925d1ca4e1f3c92bb51914c3e4c))
---

chore: release  service 0.1.12

---

.release-please-manifest.json
charts/ephemeral/CHANGELOG.md
charts/ephemeral/Chart.yaml

---
* **service/chart:** fix forced aborts of long-running computations ([#36](https://github.com/carbynestack/ephemeral/issues/36)) ([a131ae7](https://github.com/carbynestack/ephemeral/commit/a131ae74bd9d98d345d78d84a67388cbd783b36d))
---

chore: release  chart 0.1.3

---

.release-please-manifest.json
CHANGELOG.md

---
* **service/chart:** fix forced aborts of long-running computations ([#36](https://github.com/carbynestack/ephemeral/issues/36)) ([a131ae7](https://github.com/carbynestack/ephemeral/commit/a131ae74bd9d98d345d78d84a67388cbd783b36d))
---

chore: release  service 0.1.13

---

.release-please-manifest.json
ephemeral-java-client/CHANGELOG.md
ephemeral-java-client/pom.xml

---
* **java-client:** upgrade dependencies ([#77](https://github.com/carbynestack/ephemeral/issues/77)) ([4f1d0e8](https://github.com/carbynestack/ephemeral/commit/4f1d0e81ccb11b73cb7d03ccc0f598e58f89678e))
---

chore: release  java-client 0.2.0

---

.release-please-manifest.json
CHANGELOG.md

---
* **chart/service:** Add authorization ([#80](https://github.com/carbynestack/ephemeral/issues/80))
* **chart/service:** Add authorization ([#80](https://github.com/carbynestack/ephemeral/issues/80)) ([d2b2899](https://github.com/carbynestack/ephemeral/commit/d2b28994e1c08f01cbc2b510026d3c3918828354))
* **java-client:** upgrade dependencies ([#77](https://github.com/carbynestack/ephemeral/issues/77)) ([4f1d0e8](https://github.com/carbynestack/ephemeral/commit/4f1d0e81ccb11b73cb7d03ccc0f598e58f89678e))
---

chore: release  service 0.2.0

---

.release-please-manifest.json
CHANGELOG.md

---
* Secure Communication Channels via TLS ([#75](https://github.com/carbynestack/ephemeral/issues/75))
* Secure Communication Channels via TLS ([#75](https://github.com/carbynestack/ephemeral/issues/75)) ([4eb64f7](https://github.com/carbynestack/ephemeral/commit/4eb64f7a7f37e013079eb641660b4288bc5a7c3f))
---

chore: release  service 0.3.0

---

.release-please-manifest.json
charts/ephemeral/CHANGELOG.md
charts/ephemeral/Chart.yaml

---
* Secure Communication Channels via TLS ([#75](https://github.com/carbynestack/ephemeral/issues/75))
* Secure Communication Channels via TLS ([#75](https://github.com/carbynestack/ephemeral/issues/75)) ([4eb64f7](https://github.com/carbynestack/ephemeral/commit/4eb64f7a7f37e013079eb641660b4288bc5a7c3f))
---

chore: release  chart 0.3.0

---

cmd/discovery/main.go
cmd/discovery/main_test.go

The `MasterHost` and `MasterPort` configuration is required for instances only that are configured as a "slave". However, when parsing the configuration, the `MasterPort` was still mandatory.

fix(service): make master port mandatory for slave only
